exchange: binance

markets:
  - symbol: BTC/USDT
    order_qty: 0.001
    spread_bps: 8
    requote_interval_ms: 3000
    max_inventory: 0.01
    subscriptions:
      - "btcusdt@trade"
      - "btcusdt@kline_1m"

  - symbol: ETH/USDT
    order_qty: 0.01
    spread_bps: 10
    requote_interval_ms: 3000
    max_inventory: 0.2
    subscriptions:
      - "ethusdt@trade"
      - "ethusdt@kline_1m"

ws:
  uri: "wss://testnet.binance.vision/ws"
  ping_interval: 20
  ping_timeout: 10
  max_backoff: 60

api_key_env: BINANCE_API_KEY
api_secret_env: BINANCE_API_SECRET
